### ISSUE TITLE
Named params cause issue with nested routers

### ISSUE THREAD

**Issue by evulse** [aravindanve/koa-branch-router#1]
It seems like this quirk is having a pretty annoying side effect

- Named parameters assume trailing slash :userId => :userId/

If you are trying to nest routers it causes the following issue

```js
const router = new Router()

router.use("/test/:id",
  new Router()
    .get("/", async ctx => {
      ctx.body = "Slash OK"
    })
    .get("/nested", async ctx => {
      ctx.body = "OK"
    }))
```

To access the nested router you need a double slash

```
http://localhost:3001/test/1//nested
```

I've manage to do a hack around it by using, but it would be amazing if this worked as expected

```js
router.use("/test",
  new Router({ prefix: "/:id"})
    .get("/", async ctx => {
      ctx.body = "Slash OK"
    })
    .get("/nested", async ctx => {
      ctx.body = "OK"
    }))
```

**Comment by aravindanve** [comment]
@evulse Thanks for reporting the issue. I've fixed it in @1.0.5. Please feel free to re-open this issue if the problem persists.
